Repository nebari-dev/nebari-demo, pull requests merged in 2022-11, with the labels that each got.

#37 Add `nasdaq-data-link`, `matplotlib`, and `nebari` to env
  environment.yaml
Labels: area: dependencies 📦, needs: review 👀, type: maintenance

#39 Update conda-store overview
  .gitignore
  03_managing_environments.ipynb
  assets/conda-store-logo-vertical-lockup.png
  assets/conda-store-ui-design.svg
Labels: area: documentation 📖, needs: review 👀

#43 Update README
  README.md
  assets/keycloak-register-form.png
  assets/keycloak-register.png
  assets/keycloak-sign-in.png
  assets/server-options.png
  assets/start-server.png
Labels: area: documentation 📖, needs: review 👀, type: enhancement 💅🏼

#45 Sync LICENSE with `nebari-dev/.github`
  LICENSE
Labels: area: user experience, type: maintenance

#42 Update conda-store overview: fix typos and add example compute
  03_managing_environments.ipynb
Labels: area: documentation 📖, type: enhancement 💅🏼

#48 Add "how it works" section and logo to dashboards overview
  04_visualizations_and_dashboards.ipynb
  assets/containds-logo.jpeg
  finance_examples/04a_panel_demo.ipynb
Labels: area: documentation 📖, type: enhancement 💅🏼

#51 Update top-level notebooks for better consistency
  00_overview.ipynb
  01_interface.ipynb
  02_dask.ipynb
  03_managing_environments.ipynb
  04_visualizations_and_dashboards.ipynb
  05_setup.ipynb
  06_conclusion.ipynb
Labels: area: documentation 📖, type: enhancement 💅🏼

#52 Add more details to 05_setup nb
  00_overview.ipynb
  01_interface.ipynb
  02_dask.ipynb
  03_managing_environments.ipynb
  04_visualizations_and_dashboards.ipynb
  05_setup.ipynb
  06_conclusion.ipynb
  assets/containds-ui.png
  assets/nebari-cli-commands.png
Labels: area: documentation 📖, type: enhancement 💅🏼

#53 Add feedback survey
  06_conclusion.ipynb
Labels: area: documentation 📖, type: maintenance

#38 Update Dask example
  .gitignore
  02_dask.ipynb
  assets/dask-adaptive.svg
  assets/dask-example-dashboard.gif
  finance_examples/02_dask_gateway_adaptive_scaling.ipynb
  finance_examples/02a_dask_gateway_adaptive_scaling.ipynb
Labels: area: documentation 📖, needs: review 👀

#75 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: type: file sync ♻️

#79 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
Labels: type: file sync ♻️
